version: "3"

services:
  database:
    build: database/
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: movie123

  webapp:
    build: webapp/
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
#
